default: &default
  adapter: postgresql
  encoding: unicode
  pool: 5
#  host: localhost
#  port: 5432
#  database: recepies-app
#  username: sagikirma

development:
  <<: *default

test:
  <<: *default
  database: recepies_test

production:
  <<: *default
